### ISSUE TITLE
[1.20.1] Depleted Fuels don't show in JEI

### ISSUE THREAD

**Issue by Leclowndu93150** [igentuman/NuclearCraft-Neoteric#76] opened 2024-03-24 09:09 UTC
![image](https://github.com/igentuman/NuclearCraft-Neoteric/assets/73310949/7e5e988a-ffcf-403c-81e6-6c8c69a488d0)

maybe a bunch of other things don't show either

**Comment by igentuman** [comment] 2024-03-24 12:05
duplicate of Depleted Fuels do not appear in JEI #70

**Closed as completed by igentuman** 2024-03-24 12:05 UTC
