### ISSUE TITLE
Is heat management broken completely?

### ISSUE THREAD

**Issue by BrickedKeyboard** [igentuman/NuclearCraft-Neoteric#122] opened 2024-10-05 05:51 UTC
![image](https://github.com/user-attachments/assets/bf06b1e6-b873-4635-ac8e-2dbc1be9e34e)

This reactor is about to melt down.  Yet the attached comparator doesn't appear to register any heat at all.  This is really bad - running hotter fuels than the reactor can handle and having it pulse on and off is a standard way to play the previous version.

**Comment by igentuman** [comment] 2024-10-05 09:43
It works
![image](https://github.com/user-attachments/assets/91cd49e3-83d5-4cbc-85b8-7f9ff0badf92)
just checked

more details?

**Comment by igentuman** [comment] 2024-10-06 08:54
Closing as author is not responding and i was not able to reproduce the issue

**Closed as not planned by igentuman** 2024-10-06 08:54 UTC
Labels: invalid
