### ISSUE TITLE
Coolers don't work properly

### ISSUE THREAD

**Issue by leollo98** [igentuman/NuclearCraft-Neoteric#120] opened 2024-09-30 02:34 UTC
When creating a simple layer with valid glowstone coolers, cells and moderators we have that the cooling is zero when it should have been 2080HT/t

![image](https://github.com/user-attachments/assets/eee3375b-b9a0-42ad-974d-2f122241ea62)

![image](https://github.com/user-attachments/assets/7ee739de-0030-4710-ab23-7b81ef0618f6)

**Comment by igentuman** [comment] 2024-10-05 20:29
Just tried exact same setup as yours.
![image](https://github.com/user-attachments/assets/2a49c41f-3e7c-4009-a09b-b54f87668851)

**Comment by igentuman** [comment] 2024-10-05 20:33
What fuel do you have?
Even TBU gives more heat gen
![image](https://github.com/user-attachments/assets/e729f41a-00fe-4d13-8dc1-57c479f3c5e9)

**Comment by igentuman** [comment] 2024-10-06 08:54
Closing as author is not responding and i was not able to reproduce the issue

**Closed as not planned by igentuman** 2024-10-06 08:54 UTC
Labels: invalid
